server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wangzhi

  #mybatis配置
#  mybatis:
#    typeAliasesPackage: com.strong.entity
#    mapperLocations: classpath:mapper/*.xml
#    configLocation: classpath:/mybatis-config.xml